import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            username: "su",
            email: "admin@gmail.com",
            password: bcrypt.hashSync('admin', 8),
            isAdmin: true,
        },
        {
            username: "dung",
            email: "user@gmail.com",
            password: bcrypt.hashSync('user', 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/product1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/product2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image: '/images/product3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            name: 'Nike Slim Pant',
            category: 'Pants',
            image: '/images/product4.jpg',
            price: 120,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            name: 'Puma Slim Pant',
            category: 'Pants',
            image: '/images/product5.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Adidas Fit Pant',
            category: 'Pants',
            image: '/images/product6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            name: 'Nike Sport Shoes',
            category: 'Shoes',
            image: '/images/product7.jpg',
            price: 35,
            countInStock: 9,
            brand: 'Nike',
            rating: 4,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            name: 'Puma Sport Shoes',
            category: 'Shoes',
            image: '/images/product8.jpg',
            price: 55,
            countInStock: 20,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 5,
            description: 'high quality product',
        },
        {
            name: 'Balenciaga Fit Shoes',
            category: 'Shoes',
            image: '/images/product9.jpg',
            price: 120,
            countInStock: 3,
            brand: 'Balenciaga',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Converse Fit Shoes',
            category: 'Shoes',
            image: '/images/product10.jpg',
            price: 50,
            countInStock: 3,
            brand: 'Converse',
            rating: 4.5,
            numReviews: 30,
            description: 'high quality product',
        },
    ],
};

export default data;