version: 2.1

orbs:
  node: circleci/node@16.14.0

jobs:
  build:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: node
      - run:
          name: Build app
          command: npm run build

  test:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - run:
          name: Test app
          command: npm test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
